name: Auto Assign

on:
  pull_request:
    types: [ opened, ready_for_review ]

permissions:
  pull-requests: write

jobs:
  count-reviewers:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      count: ${{ steps.extract.outputs.count }}
    steps:
      - name: Extract the number of reviewers
        id: extract
        run: |
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=opened#pull_request
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=ready_for_review#pull_request
          reviewers_count=$(cat ${{ github.event_path }} | jq '.pull_request.requested_reviewers | length')
          echo "count=$reviewers_count" >> "$GITHUB_OUTPUT"

  request-reviewers:
    needs:
      - count-reviewers
    if: needs.count-reviewers.outputs.count == '0'
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign pull request author
          reviewers: ${{ vars.REVIEWERS }}
